export const SELECT_FILE = 'SELECT_FILE';
export const UPLOAD_FILE = 'UPLOAD_FILE';
export const UPLOAD_FILE_COMPLETED = 'UPLOAD_FILE_COMPLETED';
export const UPLOAD_FILE_FAILED = 'UPLOAD_FILE_FAILED';
export const FILTER_FILES = 'FILTER_FILES';
export const FILTER_FILES_COMPLETED = 'FILTER_FILES_COMPLETED';
export const FILTER_FILES_FAILED = 'FILTER_FILES_FAILED';
export const CREATE_QRCODE = 'CREATE_QRCODE';
export const CREATE_QRCODE_COMPLETED = 'CREATE_QRCODE_COMPLETED';
export const CLEAR_QRCODE = 'CLEAR_QRCODE';

