export const INITIALIZE_APP_THUNK = 'INITIALIZE_APP_THUNK';
export const INITIALIZE_APP_SAGA = 'INITIALIZE_APP_SAGA';
export const INITIALIZE_APP_COMPLETED = 'INITIALIZE_APP_COMPLETED';
export const INITIALIZE_APP_FAILED = 'INITIALIZE_APP_FAILED';